### ISSUE TITLE
Section border and cursor

### ISSUE THREAD

**Issue by atacan** [Selekkt/skelet#10]
regarding my site [atacan.gitlab.io](https://bit.ly/3eaDW3q2)

1. I don't have any class in the `<section>`s but when you mouse over the area the cursor turns into a up and down arrow. When you click, it goes to a little below the top of page.

   * I didn't know about `class="intro"` so I did the landing screen myself. Is it because of that?

1. The horizontal line that is the border of the sections spans the entire screen. In your homepage it has margins from the sides. Why is mine like that?

**Comment by thagxt** [comment]
Hi, I'm glad Skelet. is useful to you. 

1. The `s-resize` is defined in `app.css` in `section .meta`

`section .meta {
    padding: 10rem var(--percentage) 12rem;
    cursor: s-resize; /* REMOVE THIS */
}`

2. Because the width of the section is set to `100%`. I'd suggest you to use `<hr>` instead and remove the border from sections.
