### ISSUE TITLE
Misnamed box-sizing and white-space properties. Current master and 3.3 release. 

### ISSUE THREAD

**Issue by rtizzy** [Selekkt/skelet#14]
skelet.css seems to have a number of different misspellings that might have been caused by a errant find/replace.

Screenshot below. 

![image](https://user-images.githubusercontent.com/523926/113390699-88872a80-9392-11eb-9193-fda7f8497194.png)

**Comment by rtizzy** [comment]
Fixed by https://github.com/Selekkt/skelet/pull/15

**Comment by thagxt** [comment]
Thank you! I've merged your PR!

**Comment by rtizzy** [comment]
No problem! Thank you for open sourcing your work.
