### ISSUE TITLE
[docs] Section headers feel weird

### ISSUE THREAD

**Issue by Xerus2000** [Selekkt/skelet#3]
![image](https://user-images.githubusercontent.com/13354331/77789167-d2904e80-7062-11ea-82f1-df4f6007b97b.png)
The Section headers turn my cursor into an unexpected resizing look, also the "#" link is a bit out of place.

**Comment by thagxt** [comment]
Thank you reporting! 
The "#" is supposed to be small and placed right above the Title. 
The cursor is also supposed to be "s-resize".

But I fixed the description which wasn't supposed to be so close to title.
