### ISSUE TITLE
Provide NPM package

### ISSUE THREAD

**Issue by matthiasbaldi** [Selekkt/skelet#4]
hi

Would it be possible for you to package your work also as npm package?
This would make it much easier to install the css lib into an existing Javascript/Typescript project.

Thanks. :)

**Comment by thagxt** [comment]
Hi, 
That's definitely something we'll do in the near future.

**Comment by thagxt** [comment]
Here it is! `npm i selekkt-skelet` 
let me know if it works correctly.

**Comment by matthiasbaldi** [comment]
works, thank you. 👍
