### ISSUE TITLE
Custom HTML tags in React JSX?

### ISSUE THREAD

**Issue by TheCapedBaldi** [Selekkt/skelet#5]
Hi there,

First of, great work! Very useful to quickly start on small projects.

I extracted the `skelet.css` file to my React project and trying to use it. However, I'm getting these errors.

Any idea how we can change this for better support?
<img width="696" alt="Screenshot 2020-12-01 at 10 41 48" src="https://user-images.githubusercontent.com/16179773/100730393-e8100200-33c1-11eb-80ba-4d473c261dd8.png">

**Comment by thagxt** [comment]
Hi @TheCapedBaldi ,

I’m sorry unfortunately I’m not familiar with React.
But I've found [a guide](https://www.typescriptlang.org/docs/handbook/jsx.html#intrinsic-elements), that better explains how JSX works and why you might be getting that error.

If that doesn't help you, it’s best to post a question on [StackOverflow](https://stackoverflow.com/questions/tagged/reactjs)

kind regards.
