### ISSUE TITLE
Can't make triple column

### ISSUE THREAD

**Issue by rockthrower69** [Selekkt/skelet#6]
Skelet uses a 16-column grid system instead of the regular 12-column one. This gives fewer grid options, since 16 is only divisible by 1, 2, 4 and 8. 12 is divisible by 1, 2, 3, 4 and 6 giving a better range. How can I solve this issue?

**Comment by thagxt** [comment]
Hi @rockthrower69,
sorry for the late reply, busy period.

16 is the Max supported number of columns you can have in Skelet. 
If you need a 12-column grid you can simply set it like this:

`<grid columns="12">`

```
<grid columns="12">
<c span="1-6>Hey</c>
<c span="7..">There</c>
</grid>
```

here's a [JSfiddle](https://jsfiddle.net/tm0p9ehg/)
