### ISSUE TITLE
Any way to disable ::-webkit-scrollbar-track styling

### ISSUE THREAD

**Issue by aumkarthakur** [Selekkt/skelet#8]
Not everyone want to use "fancy" scrollbar. Is there any way to revert back to browser's native scrollbar design.

**Comment by thagxt** [comment]
Yes, we've noticed that's a bad idea as well. Especially on Chrome because it shows even if you've a trackpad for instance. It will be moved from `skelet.css` to the `app.css` file soon. Thanks for the input 👍
